version: '3'
services:
  amin:
    build: .
    image: aminaimeur/docker-react:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./.nginxssl:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/conf.d/default.conf