name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/<image-name>:latest

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build --file Dockerfile.dev --tag docker-react-image .
          docker tag docker-react-image:latest ${{ secrets.DOCKER_REPO_URL }}:latest
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_REPO_URL }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Define the dependency

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} '
            docker pull ${{ secrets.DOCKER_REPO_URL }}:latest && \
            docker stop react_app && \
            docker rm react_app && \
            docker run -d --name react_app \
            -p 80:80 ${{ secrets.DOCKER_REPO_URL }}:latest'
