name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          sudo cp -r ~/.nginxssl ~/actions-runner/_work/docker-react/docker-react
          docker compose build
          docker compose push
          docker compose up -d